-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Action

--- 恢复战斗中HP
--- @param ctx APIContext
--- @param HealValue number
Heal = function(ctx, HealValue)
    ctx:Set("HealValue", tonumber(HealValue))
    API:Execute("Heal", ctx)
end

--- 自伤
--- @param ctx APIContext
--- @param DamageValue number
SelfDamage = function(ctx, DamageValue)
    ctx:Set("DamageValue", tonumber(DamageValue))
    API:Execute("SelfDamage", ctx)
end

--- 消除对方护盾值
--- @param ctx APIContext
--- @param BreakValue number
ArmorBreak = function(ctx, BreakValue)
    ctx:Set("BreakValue", tonumber(BreakValue))
    API:Execute("ArmorBreak", ctx)
end

--- 给目标NPC添加Buff
--- @param ctx APIContext
--- @param Target CombatNpc
--- @param BuffId string
--- @param Stacks number
--- @param Duration number
AddNpcBuff = function(ctx, Target, BuffId, Stacks, Duration)
    ctx:Set("Target", Target)
    ctx:Set("BuffId", BuffId)
    ctx:Set("Stacks", tonumber(Stacks))
    ctx:Set("Duration", tonumber(Duration))
    API:Execute("AddNpcBuff", ctx)
end

--- 给施法者添加永久属性修正
--- @param ctx APIContext
--- @param Target CombatNpc
--- @param StatId string
--- @param Value number
--- @param ModifierType string
--- @param SourceId string
AddStatBuff = function(ctx, Target, StatId, Value, ModifierType, SourceId)
    ctx:Set("Target", Target)
    ctx:Set("StatId", StatId)
    ctx:Set("Value", tonumber(Value))
    ctx:Set("ModifierType", ModifierType)
    ctx:Set("SourceId", SourceId)
    API:Execute("AddStatBuff", ctx)
end

--- 移除目标随机一张伤势卡
--- @param ctx APIContext
--- @param Target CombatNpc
--- @param Size number
--- @param Exact boolean
RemoveRandomWound = function(ctx, Target, Size, Exact)
    ctx:Set("Target", Target)
    ctx:Set("Size", tonumber(Size))
    ctx:Set("Exact", Exact)
    API:Execute("RemoveRandomWound", ctx)
end

--- 位移目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param Position string
Displace = function(ctx, Domain, Position)
    ctx:Set("Domain", Domain)
    ctx:Set("Position", Position)
    API:Execute("Displace", ctx)
end

--- 充能目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param ReduceTick number
Charge = function(ctx, Domain, ReduceTick)
    ctx:Set("Domain", Domain)
    ctx:Set("ReduceTick", tonumber(ReduceTick))
    API:Execute("Charge", ctx)
end

--- 冻结目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param FreezeTime number
Freeze = function(ctx, Domain, FreezeTime)
    ctx:Set("Domain", Domain)
    ctx:Set("FreezeTime", tonumber(FreezeTime))
    API:Execute("Freeze", ctx)
end

--- 减速目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param Stack number
Slow = function(ctx, Domain, Stack)
    ctx:Set("Domain", Domain)
    ctx:Set("Stack", tonumber(Stack))
    API:Execute("Slow", ctx)
end

--- 加速目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param Stack number
Haste = function(ctx, Domain, Stack)
    ctx:Set("Domain", Domain)
    ctx:Set("Stack", tonumber(Stack))
    API:Execute("Haste", ctx)
end

--- 给目标卡牌添加永久属性修正
--- @param ctx APIContext
--- @param Domain string
--- @param StatId string
--- @param Value number
AddCardStatBuff = function(ctx, Domain, StatId, Value)
    ctx:Set("Domain", Domain)
    ctx:Set("StatId", StatId)
    ctx:Set("Value", tonumber(Value))
    API:Execute("AddCardStatBuff", ctx)
end

--- 灵元转化回蓝条MP
--- @param ctx APIContext
--- @param Element string
--- @param MaxAmount number
Convert = function(ctx, Element, MaxAmount)
    ctx:Set("Element", Element)
    ctx:Set("MaxAmount", tonumber(MaxAmount))
    API:Execute("Convert", ctx)
end

--- MP转化为灵元
--- @param ctx APIContext
--- @param Amount number
Draw = function(ctx, Amount)
    ctx:Set("Amount", tonumber(Amount))
    API:Execute("Draw", ctx)
end

--- 减少自身指定元素的灵元
--- @param ctx APIContext
--- @param Element string
--- @param Amount number
ReduceMana = function(ctx, Element, Amount)
    ctx:Set("Element", Element)
    ctx:Set("Amount", tonumber(Amount))
    API:Execute("ReduceMana", ctx)
end

--- 将卡从候补池部署到运转池
--- @param ctx APIContext
--- @param CardId number
Deploy = function(ctx, CardId)
    ctx:Set("CardId", tonumber(CardId))
    API:Execute("Deploy", ctx)
end

--- 将卡从运转池召回候补池
--- @param ctx APIContext
--- @param CardId number
Recall = function(ctx, CardId)
    ctx:Set("CardId", tonumber(CardId))
    API:Execute("Recall", ctx)
end

--- 给NPC添加特质
--- @param ctx APIContext
--- @param int string
--- @param TraitId string
GiveTrait = function(ctx, int, TraitId)
    ctx:Set("int", int)
    ctx:Set("TraitId", TraitId)
    API:Execute("GiveTrait", ctx)
end

--- 移除NPC特质
--- @param ctx APIContext
--- @param int string
--- @param TraitId string
RemoveTrait = function(ctx, int, TraitId)
    ctx:Set("int", int)
    ctx:Set("TraitId", TraitId)
    API:Execute("RemoveTrait", ctx)
end

--- 给NPC添加行为卡
--- @param ctx APIContext
--- @param int string
--- @param CardDefineId string
GiveBehaviorCard = function(ctx, int, CardDefineId)
    ctx:Set("int", int)
    ctx:Set("CardDefineId", CardDefineId)
    API:Execute("GiveBehaviorCard", ctx)
end

--- 修改地块五行浓度
--- @param ctx APIContext
--- @param PlaneId string
--- @param Element string
--- @param Delta number
ModifyAura = function(ctx, PlaneId, Element, Delta)
    ctx:Set("PlaneId", PlaneId)
    ctx:Set("Element", Element)
    ctx:Set("Delta", tonumber(Delta))
    API:Execute("ModifyAura", ctx)
end

--- 修改NPC属性值
--- @param ctx APIContext
--- @param int string
--- @param StatId string
--- @param Delta number
ModifyStat = function(ctx, int, StatId, Delta)
    ctx:Set("int", int)
    ctx:Set("StatId", StatId)
    ctx:Set("Delta", tonumber(Delta))
    API:Execute("ModifyStat", ctx)
end

--- 链式触发Story
--- @param ctx APIContext
--- @param StoryId string
--- @param SubjectId string
TriggerStory = function(ctx, StoryId, SubjectId)
    ctx:Set("StoryId", StoryId)
    ctx:Set("SubjectId", SubjectId)
    API:Execute("TriggerStory", ctx)
end

--- 按Tag匹配触发Story
--- @param ctx APIContext
--- @param Tags string
TriggerStoryByTag = function(ctx, Tags)
    ctx:Set("Tags", Tags)
    API:Execute("TriggerStoryByTag", ctx)
end

--- 向宿命池写入条目
--- @param ctx APIContext
--- @param SubjectId string
--- @param Time number
--- @param StoryId string
AddToFatePool = function(ctx, SubjectId, Time, StoryId)
    ctx:Set("SubjectId", SubjectId)
    ctx:Set("Time", tonumber(Time))
    ctx:Set("StoryId", StoryId)
    API:Execute("AddToFatePool", ctx)
end

--- 向劫缘池写入条目
--- @param ctx APIContext
--- @param SubjectId string
--- @param StoryId string
--- @param Weight number
AddToKarmaPool = function(ctx, SubjectId, StoryId, Weight)
    ctx:Set("SubjectId", SubjectId)
    ctx:Set("StoryId", StoryId)
    ctx:Set("Weight", tonumber(Weight))
    API:Execute("AddToKarmaPool", ctx)
end

--- 通过EventMgr广播事件
--- @param ctx APIContext
--- @param EventName string
TriggerEvent = function(ctx, EventName)
    ctx:Set("EventName", EventName)
    API:Execute("TriggerEvent", ctx)
end

