-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Action

--- 位移目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param Position string
Displace = function(ctx, Domain, Position)
    ctx:Set("Domain", Domain)
    ctx:Set("Position", Position)
    API:Execute("Displace", ctx)
end

--- 充能目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param ReduceTick number
Charge = function(ctx, Domain, ReduceTick)
    ctx:Set("Domain", Domain)
    ctx:Set("ReduceTick", tonumber(ReduceTick))
    API:Execute("Charge", ctx)
end

--- 冻结目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param FreezeTime number
Freeze = function(ctx, Domain, FreezeTime)
    ctx:Set("Domain", Domain)
    ctx:Set("FreezeTime", tonumber(FreezeTime))
    API:Execute("Freeze", ctx)
end

--- 减速目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param Stack number
Slow = function(ctx, Domain, Stack)
    ctx:Set("Domain", Domain)
    ctx:Set("Stack", tonumber(Stack))
    API:Execute("Slow", ctx)
end

--- 加速目标卡牌
--- @param ctx APIContext
--- @param Domain string
--- @param Stack number
Haste = function(ctx, Domain, Stack)
    ctx:Set("Domain", Domain)
    ctx:Set("Stack", tonumber(Stack))
    API:Execute("Haste", ctx)
end

--- 给目标卡牌添加永久属性修正
--- @param ctx APIContext
--- @param Domain string
--- @param StatId string
--- @param Value number
AddCardStatBuff = function(ctx, Domain, StatId, Value)
    ctx:Set("Domain", Domain)
    ctx:Set("StatId", StatId)
    ctx:Set("Value", tonumber(Value))
    API:Execute("AddCardStatBuff", ctx)
end

