-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Scope

--- 获得目标所有卡牌
--- @param ctx APIContext
--- @param Target CombatNpc
--- @param Result List<CombatCard>
AllCard = function(ctx, Target, Result)
    ctx:Set("Target", Target)
    ctx:Set("Result", Result)
    API:Execute("AllCard", ctx)
end

--- 获得目标在CD中的一张卡牌
--- @param ctx APIContext
--- @param Target CombatNpc
--- @param Result CombatCard
RandomCardInCD = function(ctx, Target, Result)
    ctx:Set("Target", Target)
    ctx:Set("Result", Result)
    API:Execute("RandomCardInCD", ctx)
end

