-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Condition

--- 判断目标卡牌是否为法宝
--- @param ctx APIContext
--- @param Target CombatCard
--- @return boolean
IsFabao = function(ctx, Target)
    ctx:Set("Target", Target)
    API:Execute("IsFabao", ctx)
    return ctx:GetObject("Result")
end

--- 判断目标卡牌是否为法术
--- @param ctx APIContext
--- @param Target CombatCard
--- @return boolean
IsFaShu = function(ctx, Target)
    ctx:Set("Target", Target)
    API:Execute("IsFaShu", ctx)
    return ctx:GetObject("Result")
end

--- 判断目标卡牌是否为功法
--- @param ctx APIContext
--- @param Target CombatCard
--- @return boolean
IsGongFa = function(ctx, Target)
    ctx:Set("Target", Target)
    API:Execute("IsGongFa", ctx)
    return ctx:GetObject("Result")
end

--- 判断目标卡牌是否为物品
--- @param ctx APIContext
--- @param Target CombatCard
--- @return boolean
IsItem = function(ctx, Target)
    ctx:Set("Target", Target)
    API:Execute("IsItem", ctx)
    return ctx:GetObject("Result")
end

--- 判断目标卡牌是否为装备
--- @param ctx APIContext
--- @param Target CombatCard
--- @return boolean
IsEquip = function(ctx, Target)
    ctx:Set("Target", Target)
    API:Execute("IsEquip", ctx)
    return ctx:GetObject("Result")
end

--- 判断目标卡牌是否为招式
--- @param ctx APIContext
--- @param Target CombatCard
--- @return boolean
IsZhaoShi = function(ctx, Target)
    ctx:Set("Target", Target)
    API:Execute("IsZhaoShi", ctx)
    return ctx:GetObject("Result")
end

