-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Contest

--- 造成伤害（攻击拼点）
--- @param ctx APIContext
--- @param Element string
--- @param PhysicalType string
--- @param AttackValue number
Attack = function(ctx, Element, PhysicalType, AttackValue)
    ctx:Set("Element", Element)
    ctx:Set("PhysicalType", PhysicalType)
    ctx:Set("AttackValue", tonumber(AttackValue))
    API:Execute("Attack", ctx)
end

--- 防御拼点
--- @param ctx APIContext
--- @param DefendType string
--- @param DefendValue number
Defend = function(ctx, DefendType, DefendValue)
    ctx:Set("DefendType", DefendType)
    ctx:Set("DefendValue", tonumber(DefendValue))
    API:Execute("Defend", ctx)
end

