-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Action

--- 修改地块五行浓度
--- @param ctx APIContext
--- @param PlaneId string
--- @param Element string
--- @param Delta number
ModifyAura = function(ctx, PlaneId, Element, Delta)
    ctx:Set("PlaneId", PlaneId)
    ctx:Set("Element", Element)
    ctx:Set("Delta", tonumber(Delta))
    API:Execute("ModifyAura", ctx)
end

--- 链式触发Story
--- @param ctx APIContext
--- @param StoryId string
--- @param SubjectId string
TriggerStory = function(ctx, StoryId, SubjectId)
    ctx:Set("StoryId", StoryId)
    ctx:Set("SubjectId", SubjectId)
    API:Execute("TriggerStory", ctx)
end

--- 按Tag匹配触发Story
--- @param ctx APIContext
--- @param Tags string
TriggerStoryByTag = function(ctx, Tags)
    ctx:Set("Tags", Tags)
    API:Execute("TriggerStoryByTag", ctx)
end

--- 通过EventMgr广播事件
--- @param ctx APIContext
--- @param EventName string
TriggerEvent = function(ctx, EventName)
    ctx:Set("EventName", EventName)
    API:Execute("TriggerEvent", ctx)
end

