-- AUTO-GENERATED by APIMgr.ExportLua(), DO NOT EDIT
-- APIType: Action

--- 给NPC添加特质
--- @param ctx APIContext
--- @param int string
--- @param TraitId string
GiveTrait = function(ctx, int, TraitId)
    ctx:Set("int", int)
    ctx:Set("TraitId", TraitId)
    API:Execute("GiveTrait", ctx)
end

--- 移除NPC特质
--- @param ctx APIContext
--- @param int string
--- @param TraitId string
RemoveTrait = function(ctx, int, TraitId)
    ctx:Set("int", int)
    ctx:Set("TraitId", TraitId)
    API:Execute("RemoveTrait", ctx)
end

--- 给NPC添加行为卡
--- @param ctx APIContext
--- @param int string
--- @param CardDefineId string
GiveBehaviorCard = function(ctx, int, CardDefineId)
    ctx:Set("int", int)
    ctx:Set("CardDefineId", CardDefineId)
    API:Execute("GiveBehaviorCard", ctx)
end

--- 修改NPC属性值
--- @param ctx APIContext
--- @param int string
--- @param StatId string
--- @param Delta number
ModifyStat = function(ctx, int, StatId, Delta)
    ctx:Set("int", int)
    ctx:Set("StatId", StatId)
    ctx:Set("Delta", tonumber(Delta))
    API:Execute("ModifyStat", ctx)
end

--- 向宿命池写入条目
--- @param ctx APIContext
--- @param SubjectId string
--- @param Time number
--- @param StoryId string
AddToFatePool = function(ctx, SubjectId, Time, StoryId)
    ctx:Set("SubjectId", SubjectId)
    ctx:Set("Time", tonumber(Time))
    ctx:Set("StoryId", StoryId)
    API:Execute("AddToFatePool", ctx)
end

--- 向劫缘池写入条目
--- @param ctx APIContext
--- @param SubjectId string
--- @param StoryId string
--- @param Weight number
AddToKarmaPool = function(ctx, SubjectId, StoryId, Weight)
    ctx:Set("SubjectId", SubjectId)
    ctx:Set("StoryId", StoryId)
    ctx:Set("Weight", tonumber(Weight))
    API:Execute("AddToKarmaPool", ctx)
end

